import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { dmSans } from "./lib/fonts";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.className} h-full antialiased w-full`}
    >
      <body className="h-full w-full">{children}</body>
    </html>
  );
}
